server.port=9090

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/stats_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:stats_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:stats_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
